### ISSUE TITLE
[BUG] Youtube 403 Error

### ISSUE THREAD

**Issue by XPMarCusXP** [pepyta/robibot-depracted#2]
![image](https://user-images.githubusercontent.com/41166340/80312022-3f724200-87e3-11ea-8005-f7d59b127e91.png)

**Comment by pepyta** [comment]
Hi! Thanks for contacting me with this issue.
Have you set up the .env file on **Glitch**? If you just created it on your local machine you must also create it at the Glitch page.

```
TOKEN=*YOUR DISCORD BOT TOKEN*
YOUTUBE_API=*YOUR YOUTUBE API TOKEN*
PROJECT_DOMAIN=*YOUR PROJECT NAME (WITHOUT .glitch.me)
```
![image](https://user-images.githubusercontent.com/23434629/80796038-7d35e880-8b9e-11ea-8890-894c4f0b09c7.png)
